

language: R
sudo: required
warnings_are_errors: true

before install:
 - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev libv8-dev

r_packages:
 - dbscan
 - forcats
 - igraph
 - sp
 - sf
 - magrittr
 - data.table
 - broom
 - trajectories
 - ggplot2
 - roxygen2
 - testthat

after_success:
 - Rscript -e 'devtools::install();devtools::test()'
 - Rscript -e 'library(covr); codecov()'
