

language: R
sudo: required
warnings_are_errors: true


r_packages:
 - dbscan
 - forcats
 - igraph
 - sp
 - magrittr
 - data.table
 - broom
 - trajectories
 - ggplot2
 - roxygen2
 - testthat

after_success:
 - Rscript -e 'devtools::install();devtools::test()'
 - Rscript -e 'library(covr); codecov()'
